image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  
run:
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - python3 -m twine upload -r local dist/* --config-file $PYPIRC

